global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  - job_name: 'node'
    file_sd_configs:
      - files:
          - /etc/prometheus/exporter-targets.yml
        refresh_interval: 5m
    relabel_configs:
      - source_labels: [exporter]
        regex: 'node'
        action: keep
      - regex: 'exporter'
        action: labeldrop

  - job_name: 'cadvisor'
    static_configs:
      - targets: ['host.docker.internal:18081']

  - job_name: 'libvirt'
    file_sd_configs:
      - files:
          - /etc/prometheus/exporter-targets.yml
        refresh_interval: 5m
    relabel_configs:
      - source_labels: [exporter]
        regex: 'libvirt'
        action: keep
      - regex: 'exporter'
        action: labeldrop

  - job_name: 'ollama'
    file_sd_configs:
      - files:
          - /etc/prometheus/exporter-targets.yml
        refresh_interval: 5m
    relabel_configs:
      - source_labels: [exporter]
        regex: 'ollama'
        action: keep
      - regex: 'exporter'
        action: labeldrop

  - job_name: 'nvidia-gpu'
    file_sd_configs:
      - files:
          - /etc/prometheus/exporter-targets.yml
        refresh_interval: 5m
    relabel_configs:
      - source_labels: [exporter]
        regex: 'nvidia-gpu'
        action: keep
      - regex: 'exporter'
        action: labeldrop
