# WordPress - Complete WordPress stack with MySQL database
# Provides a full WordPress installation with persistent data storage
services:

  wordpress:
    image: wordpress                          # Official WordPress image (latest)
    restart: always                           # Always restart on failure
    ports:
      - "80:80"                               # HTTP port (consider adding quotes for consistency)
    environment:
      WORDPRESS_DB_HOST: db                   # Database connection hostname
      WORDPRESS_DB_USER: exampleuser         # Database user (change for production)
      WORDPRESS_DB_PASSWORD: examplepass     # Database password (change for production)
      WORDPRESS_DB_NAME: exampledb           # Database name
      TZ: Asia/Taipei                         # Set timezone for consistency
    volumes:
      - ./volume-wordpress:/var/www/html      # Persist WordPress files and uploads
    depends_on:
      - db                                    # Ensure database starts before WordPress

  db:
    image: mysql:8.0                          # MySQL 8.0 for database backend
    restart: always                           # Always restart on failure
    environment:
      MYSQL_DATABASE: exampledb              # Create this database on startup
      MYSQL_USER: exampleuser               # Create this user (change for production)
      MYSQL_PASSWORD: examplepass           # User password (change for production)
      MYSQL_RANDOM_ROOT_PASSWORD: '1'       # Generate random root password for security
      TZ: Asia/Taipei                        # Set timezone for consistency
    volumes:
      - ./volume-db:/var/lib/mysql           # Persist database data
